version: '3'

services:
  selenium:
    links:
      - db
    build:
        context: .
        shm_size: '2gb'
    ports:
      - 4000:4000
    volumes:
      - ./src:/usr/src/app
    shm_size: '2gb'
    #   use volumes to mount local codebase with docker vm codebase
    # main advantage is local chanes are reflectd in vm code
  db:
    container_name: mydb
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d/:ro