class Constant:

    ARTICLE_CATEGORY_KNOWLEDGE = 0
    ARTICLE_CATEGORY_FOREIGN = 1
    ARTICLE_CATEGORY_FEATURED = 2
    ARTICLE_CATEGORY_CELEBRITY = 3
    ARTICLE_CATEGORY_TRAVEL = 4
    ARTICLE_CATEGORY_NEWS = 5

    MAX_PAGES_FOR_ARTICLE = 1