class Constant:

    ARTICLE_CATEGORY_KNOWLEDGE = 0
    ARTICLE_CATEGORY_FOREIGN = 1
    ARTICLE_CATEGORY_FEATURED = 2
    ARTICLE_CATEGORY_CELEBRITY = 3
    ARTICLE_CATEGORY_TRAVEL = 4
    ARTICLE_CATEGORY_NEWS = 5

    MAX_PAGES_FOR_ARTICLE = 150
    # 12 for knowlage
    #  220 for celeb
    #  500 for foreign
    #  500 for news
    #  13 for travel
    #  91 for featured
    #1 equals to 30 articles

    PARAGRAPH_CAN_CREATE_QUESTIONS = 1
    PARAGRAPH_CANNOT_CREATE_QUESTIONS = 0

    ALL_THE_ARTICLE_PARAGRAPHS_ADDED = 1
    ERROR_DURING_PARAGRAPH_PROCESS = 2
    ARTICLE_PARAGRAPHS_NOT_ADDED = 0

    SLACK_WEB_HOOK_URL = 'https://hooks.slack.com/services/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'
